# Generated by Django 3.1.5 on 2021-02-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip_whitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250, verbose_name='App Name')),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP Address')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'White List IP',
                'verbose_name_plural': 'White List IPs',
            },
        ),
        migrations.AlterField(
            model_name='parameters',
            name='maxDailyEarnings',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AlterField(
            model_name='payments',
            name='email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='payments',
            name='memo',
            field=models.CharField(default='', max_length=250),
        ),
    ]
