# Generated by Django 3.1.5 on 2021-02-07 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210207_0456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameters',
            options={'verbose_name': 'Site Parameters', 'verbose_name_plural': 'Site Parameters'},
        ),
    ]
