# Generated by Django 3.1.5 on 2021-02-09 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210207_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='ip_whitelist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ip_whitelist', to='main.ip_whitelist'),
            preserve_default=False,
        ),
    ]
