# Generated by Django 3.1.5 on 2021-02-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210212_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='paypal_note',
            field=models.CharField(default='Thanks for your participation!', max_length=200),
        ),
    ]
