# Generated by Django 3.1.5 on 2021-02-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_parameters_paypal_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payout_batch_id_local',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='payments',
            name='payout_batch_id_paypal',
            field=models.CharField(default='', max_length=250),
        ),
    ]
