# Generated by Django 3.1.5 on 2021-02-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210214_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='note',
            field=models.CharField(default='', max_length=250),
        ),
    ]
