# Generated by Django 3.1.5 on 2021-02-16 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_payments_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='paypal_note',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='ip_whitelist',
        ),
        migrations.AddField(
            model_name='payments',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='app_name', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parameters',
            name='paypal_token',
            field=models.CharField(default='asdf123', max_length=200),
        ),
    ]
