# Generated by Django 4.0.4 on 2022-06-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210216_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ['-timestamp__date', '-amount'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AddField(
            model_name='payments',
            name='sender_item_id',
            field=models.CharField(default='', max_length=250),
        ),
    ]
